version: "3"

services:
  bitcoind:
    image: kylemanna/bitcoind
    volumes:
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    ports:
      - "18443:18443"
      - "18444:18444"

  electrumx:
    image: alko89/electrumx
    ports:
      - "50002:50002"
    environment:
      - DAEMON_URL=http://bitcoinrpc:rpcpass@bitcoind:18443
      - COIN=BitcoinSegwit
      - NET=regtest
      - DB_ENGINE=leveldb

  explorer:
    build: .
    ports:
      - "3002:3002"
    command: ["./wait-for-electrumx.sh", "electrumx", "50002"]
